### ISSUE TITLE
Message Bus V.S. Queue

### ISSUE THREAD

**Issue by RenoMuijsenberg** [fuas-dverse/DVerse#13]
# Description
When creating the Dverse network we asked ourself what kind of message distributer we wanted to use, we came up with message bus or message queue. We will research some pro's and cons about the two types. While doing the research we also can make some small prototypes of the two types.

# Tasks
- [x] Research Message Bus
- [x] Research Message Queue
- [x] Research pro's and cons
- [x] Create Message Queue example (RPC or pub/sub)
- [x] Create Message Bus example
