### ISSUE TITLE
Add structured JSON data in messaging communitcation !Prototype!

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/DVerse#44]
# Description
We are converting the Architecture to the Event Driven Architecture. This case it is important to have structured JSON data in order to make the messaging more readable and scalable. In the first case we wanted to use ActivityPub, that protocol uses the JSON-LD format, maybe this is a good option or we want to create our own structure.

# Tasks
- [ ] Small research about what data should be in a structured JSON data (ActivityPub or Own version)
- [x] Create prototype of Kafka for Event Driven Architecture
- [x] Add functionality so the PUB / SUB system is based on JSON data
- [ ] Add different Events like:n Create, Delete - Filter, Response (Like ActivityPub)
- [x] Dockerize this Application

# Example
```json
{"@context": "https://www.w3.org/ns/activitystreams",
 "type": "Create",
 "id": "https://social.example/alyssa/posts/a29a6843-9feb-4c74-a7f7-081b9c9201d3",
 "to": ["https://chatty.example/ben/"],
 "actor": "https://social.example/alyssa/",
 "object": {"type": "Note",
            "id": "https://social.example/alyssa/posts/49e2d03d-b53a-4c4c-a95c-94a6abf45a19",
            "attributedTo": "https://social.example/alyssa/",
            "to": ["https://chatty.example/ben/"],
            "content": "Say, did you finish reading that book I lent you?"}}
```
