### ISSUE TITLE
Create Azure Cloud Function for checking if agents are still running

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/DVerse#52]
# Descriptipn
We need to create an Azure Cloud Function to monitor the activity of agents subscribed to Kafka. The agents send a state message with “OK” every minute. The Azure function will check all available agents to ensure they have sent a message in the last 5 minutes. If an agent has not sent a message within this timeframe, the “isactive” entry in the database needs to be updated to false.

# Tasks
- [x] Create Azure Function
- [ ] Create a prototype for Azure function (without kafka for now)
- [ ] Check if the function runs every x amount of time

# Next Steps Tasks
- [ ] Add kafka with consumers
- [ ] Check if consumer has send semething in the last 5 minutes
- [ ] Update database row to inactive
- [ ] Exit

**Comment by Brett-Mulder** [comment]
This issue can be closed, we dont use Azure Cloud functions for this because it does not support Subscribing to topics with a wildcard. But we need this to get the status.

**Comment by Brett-Mulder** [comment]
Needs to use something else
